### ISSUE TITLE
Data Clean

### ISSUE THREAD

**Issue by Buted** [231sm/Low_Resource_KBP#4]
Thanks for committing your work.

As mentioned in README.md, your annotation is based on cleaned sentences.
> Note that the sentence should be cleaned, e.g., To expand abbreviations

Can you give more details about cleaning the data? What kind of data would be cleaned? Or which tool do you use?

Thanks for your answer.

**Comment by 231sm** [comment]
We first manually check the data and clean the data with regular expression
