### ISSUE TITLE
about the sentence length 

### ISSUE THREAD

**Issue by amzfc** [231sm/Low_Resource_KBP#5]
Hi，i want to know how sentence length is calculated.  
as i want to locate the trigger word  according to the gived information ,
but gived sentence information is str type , 
so i do't konw how to do when the str has punctuation or special characters.
can you  answer my questions?

**Comment by 231sm** [comment]
Hello, Fangchen, Thanks for your interest in our work!

Yeap, the given sentence is in str type, and we split it by "blank" into a token list. We also firstly reformulate and clean the sentence and the detailed operations including 

(1) remove punctuations and some special characters, including ",", ".", "“", "”", ":", "\"", "\'\'", "\'", "(", ")" and "\n";

(2) replace other special characters with blanks or others. For example, 
"..." --> " ";
"\'s" --> " is";
"’s" --> " is";
"s’" --> "s";
"goto" --> "go to"
"Novemberintroduced" --> "November introduced"

Hope this response will help you. If you have any other questions, you can also send e-mails to me (231sm@zju.edu.cn).

**Comment by amzfc** [comment]
thanks for your reply.
