### ISSUE TITLE
您好 有源码吗

### ISSUE THREAD

**Issue by 1611064578** [231sm/Low_Resource_KBP#6]
您好 有缘吗吗

**Comment by 231sm** [comment]
Hello, thank you very much for your interest in our work. 

I feel sorry that the source code is on the old server and out of maintenance at present. 
Fortunately, the code logic is not complicated, which is mainly rebuilt based on the [implementation](https://github.com/thunlp/HATT-Proto) of HATT-Proto and the [implementation](https://github.com/dandelin/Dynamic-memory-networks-plus-Pytorch) of Dynamic Memory Network plus, you can contact me if you have any problem in reproduction. 

Best Regards.

**Comment by 1611064578** [comment]
thank you&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shumin ***@***.***&gt;; 
发送时间: 2023年2月23日(星期四) 中午11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [231sm/Low_Resource_KBP] 您好 有源码吗 (Issue #6)





 
Hello, thank you very much for your interest in our work.↳
 
I feel sorry that the source code is on the old server and out of maintenance at present.
 Fortunately, the code logic is not complicated, which is mainly rebuilt based on the implementation of HATT-Proto and the implementation of Dynamic Memory Network plus, you can contact me if you have any problem in reproduction.

我很抱歉源代码在旧服务器上并且目前已停止维护。
好在代码逻辑并不复杂，主要是基于HATT-Proto的实现和动态内存网络plus的实现进行重建的，如果你在复制方面有任何问题，可以联系我。
 
Best Regards.↳
